## Data Access
This notebook, `03_data_access.ipynb` demonstrates how to load the fully
processed, high-quality single-cell feature matrix. It requires a high-memory machine.

In [ ]:
import anndata as ad
import pickle
import pandas as pd
import scmorph as sm

file = "workspace/profiles_assembled/profiles_processed/all_adata_featFilt_batchCorr.h5ad"

# Save memory
use_backed = True

adata = sm.read(file, backed="r" if use_backed else False)

In [10]:
# Feature names are in .var
# We will split them for easier use
adata.var = sm.io.split_feature_names(adata.var.index)
adata.var

,feature_0,feature_1,feature_2,feature_3
Cells_AreaShape_Eccentricity,Cells,AreaShape,Eccentricity,None
Cells_AreaShape_HuMoments-0,Cells,AreaShape,HuMoments-0,None
Cells_AreaShape_HuMoments-1,Cells,AreaShape,HuMoments-1,None
Cells_AreaShape_InertiaTensor-0-0,Cells,AreaShape,InertiaTensor-0-0,None
Cells_AreaShape_InertiaTensor-0-1,Cells,AreaShape,InertiaTensor-0-1,None
...,...,...,...,...
Nuclei_Granularity_8_W1,Nuclei,Granularity,8,W1
Nuclei_Granularity_8_W2,Nuclei,Granularity,8,W2
Nuclei_Granularity_8_W3,Nuclei,Granularity,8,W3
Nuclei_Granularity_8_W4,Nuclei,Granularity,8,W4
Nuclei_Granularity_8_W5,Nuclei,Granularity,8,W5

In [ ]:
# And observations with corresponding metadata are in .obs
adata.obs

,SampleName,Replicate,PlateLayout,CellLine,Date,PlateID,Well,Site,Cells_ObjectNumber,Nuclei_ObjectNumber,...,Cells_AreaShape_CentroidY,Cells_AreaShape_CentroidX,Nuclei_AreaShape_CentroidY,Nuclei_AreaShape_CentroidX,Cytoplasm_AreaShape_CentroidY,Cytoplasm_AreaShape_CentroidX,treatment,ttype,ImageQCDistance,PassQC
0-11379,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,12,12,...,72.939480,238.450614,70.618647,242.483393,74.226315,236.214555,hsa-miR-194-5p,treatment,0.034368,True
1-11372,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,13,13,...,110.146238,1427.787868,153.800469,1431.897496,100.666185,1426.895412,hsa-miR-194-5p,treatment,0.034368,True
2-11371,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,14,14,...,73.369581,883.206158,80.123967,891.630460,71.589013,880.985372,hsa-miR-194-5p,treatment,0.034368,True
3-11371,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,15,15,...,129.236470,1322.658575,135.333805,1304.764956,128.026001,1326.210892,hsa-miR-194-5p,treatment,0.034368,True
4-11370,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,16,16,...,82.100334,977.689409,83.368386,967.491628,81.467580,982.778075,hsa-miR-194-5p,treatment,0.034368,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68-23994,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,81,81,...,1903.446276,1643.165129,1900.707198,1644.204752,1905.891454,1642.237056,DMSO,DMSO,0.017957,True
69-23460,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,82,82,...,1921.489761,1222.481797,1919.149446,1219.659594,1925.253709,1227.020772,DMSO,DMSO,0.017957,True
70-22916,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,83,83,...,2080.453287,1681.866205,2083.720867,1680.995935,2078.032129,1682.511044,DMSO,DMSO,0.017957,True
71-22381,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,84,84,...,2109.772043,603.913057,2107.323029,603.142195,2111.388067,604.421724,DMSO,DMSO,0.017957,True
72-21878,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,85,85,...,2113.280208,1692.549589,2112.675094,1686.600187,2113.800967,1697.669621,DMSO,DMSO,0.017957,True

In [ ]:
# We can access the cell x feature matrix using
adata.X

# If use_backed = True, this is a HDF5 dataset.
# Else, it is a 2D array that can be used as any other numpy array.

In [ ]:
# If you need a cell x feature matrix that is a bit easier to read, you can use
# the following, but do note this loads the data into memory if you are using use_backed=True
pd.concat([adata.obs[["CellLine","Replicate","PlateLayout"]], adata.to_df()],axis=1)

In [11]:
# The dataset contains just below 23M cells total
adata.shape

(22999877, 142)

In [12]:
# To make sure that this AnnData object works with all libraries,
# we have to reset the index names
adata.obs.reset_index(drop=True)
adata.obs.index = adata.obs.index.astype(str)

In [13]:
adata.obs

,SampleName,Replicate,PlateLayout,CellLine,Date,PlateID,Well,Site,Cells_ObjectNumber,Nuclei_ObjectNumber,...,Cells_AreaShape_CentroidY,Cells_AreaShape_CentroidX,Nuclei_AreaShape_CentroidY,Nuclei_AreaShape_CentroidX,Cytoplasm_AreaShape_CentroidY,Cytoplasm_AreaShape_CentroidX,treatment,ttype,ImageQCDistance,PassQC
0-11379,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,12,12,...,72.939480,238.450614,70.618647,242.483393,74.226315,236.214555,hsa-miR-194-5p,treatment,0.034368,True
1-11372,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,13,13,...,110.146238,1427.787868,153.800469,1431.897496,100.666185,1426.895412,hsa-miR-194-5p,treatment,0.034368,True
2-11371,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,14,14,...,73.369581,883.206158,80.123967,891.630460,71.589013,880.985372,hsa-miR-194-5p,treatment,0.034368,True
3-11371,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,15,15,...,129.236470,1322.658575,135.333805,1304.764956,128.026001,1326.210892,hsa-miR-194-5p,treatment,0.034368,True
4-11370,CS-C2C-R1-P1_C2C12_2019-09-13_12492_A01_1,1,P1,C2C12,2019-09-13,12492,A01,1,16,16,...,82.100334,977.689409,83.368386,967.491628,81.467580,982.778075,hsa-miR-194-5p,treatment,0.034368,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68-23994,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,81,81,...,1903.446276,1643.165129,1900.707198,1644.204752,1905.891454,1642.237056,DMSO,DMSO,0.017957,True
69-23460,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,82,82,...,1921.489761,1222.481797,1919.149446,1219.659594,1925.253709,1227.020772,DMSO,DMSO,0.017957,True
70-22916,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,83,83,...,2080.453287,1681.866205,2083.720867,1680.995935,2078.032129,1682.511044,DMSO,DMSO,0.017957,True
71-22381,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,84,84,...,2109.772043,603.913057,2107.323029,603.142195,2111.388067,604.421724,DMSO,DMSO,0.017957,True
72-21878,CS-SHS-R2-P15_SHSY5Y_2019-07-30_12378_P24_4,2,P15,SH-SY5Y,2019-07-30,12378,P24,4,85,85,...,2113.280208,1692.549589,2112.675094,1686.600187,2113.800967,1697.669621,DMSO,DMSO,0.017957,True